# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: 3MC - PIMS - ICMS - Winnipeg 2025
# Description of the Site
description: Summer school in Winnipeg in 2025
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /test-mm/assets/images/bg-test-1.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: julien.arino@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  julien-arino
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Stephanie Portet
# URL for the Image of the Author
author-image: assets/images/Map_Member.png
# 60 Words About the Author
author-about: The summer school is co-organised under the umbrellas of 3MC, PIMS and ICMS. It is funded by PIMS and others.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Collections
collections:
  people:
    output: false
  projects:
    output: true
    permalink: /projects/:path/



# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
