# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Maud Menten Institute
# Description of the Site
description: Mathematics for Life Sciences in the Canadian West
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /test-mm/assets/images/bg-test-1.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: thedevslot@gmail.com
facebook_username: thedevslot
twitter_username: thedevslot
instagram_username: thedevslot
linkedin_username: thedevslot
github_username:  thedevslot
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Stephanie Portet
# URL for the Image of the Author
author-image: assets/images/Map_Member.png
# 60 Words About the Author
author-about: The MMI is a PIMS Research Network. The primary purpose of the Maud Menten Institute (MMI) is to provide a collaborative research platform for mathematical biologists at PIMS sites to promote interactions with life science experts and decision makers in government, industry and NGOs. The secondary purpose of the Maud Menten Institute is to develop the required training program for the non-academic pipeline in mathematical biology. This program will allow new generations of mathematical biologists to impact biological fields inside and outside of academia and will explicitly establish mathematical biology as a powerful tool of investigation in biology.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Collections
collections:
  people:
    output: false
  projects:
    output: true
    permalink: /projects/:path/



# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
